# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will initiate a Veracode Static Analysis Pipeline scan, return a results.json and convert to SARIF for upload as a code scanning alert

name: "[FEATURE] SAST SCAN"

on:
  push:
    branches: 
      - 'main'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
permissions:
  contents: read

jobs:
  Build-and-SAST:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
      with:
        repository: ''

    - name: Build with Maven
      run: cd app/ && mvn clean package -DskipTests

    - name: Packing
      run: zip -r veracode-scan-target.zip ./

    - name: Veracode Upload And Scan
      uses: veracode/veracode-uploadandscan-action@0.2.10
      with:
        appname: 'Pablo Almeida Technical Panel'
        createprofile: false
        filepath: 'veracode-scan-target.zip'
        vid: '${{ secrets.VERACODE_API_ID }}'
        vkey: '${{ secrets.VERACODE_API_KEY }}'
        sandboxname: 'Github'
        scantimeout: 60
        criticality: 'VeryHigh'
